# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fft_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 535))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.file_toolButton = QtWidgets.QToolButton(self.groupBox)
        self.file_toolButton.setObjectName("file_toolButton")
        self.gridLayout_9.addWidget(self.file_toolButton, 1, 3, 1, 1)
        self.file_path_label = QtWidgets.QLabel(self.groupBox)
        self.file_path_label.setObjectName("file_path_label")
        self.gridLayout_9.addWidget(self.file_path_label, 1, 0, 1, 1)
        self.file_path_lineinput = QtWidgets.QLineEdit(self.groupBox)
        self.file_path_lineinput.setObjectName("file_path_lineinput")
        self.gridLayout_9.addWidget(self.file_path_lineinput, 1, 1, 1, 2)
        self.tool_label = QtWidgets.QLabel(self.groupBox)
        self.tool_label.setObjectName("tool_label")
        self.gridLayout_9.addWidget(self.tool_label, 0, 0, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_btn.sizePolicy().hasHeightForWidth())
        self.run_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/run-c.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_btn.setIcon(icon)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout_9.addWidget(self.run_btn, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 0, 1, 1)
        self.config_gbx = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.config_gbx.setMaximumSize(QtCore.QSize(16777215, 164))
        self.config_gbx.setObjectName("config_gbx")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.config_gbx)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.sample_rate_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.sample_rate_txt.setObjectName("sample_rate_txt")
        self.gridLayout_10.addWidget(self.sample_rate_txt, 0, 1, 1, 1)
        self.sectBits_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.sectBits_txt.setObjectName("sectBits_txt")
        self.gridLayout_10.addWidget(self.sectBits_txt, 3, 1, 1, 1)
        self.smpBitsMode_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.smpBitsMode_txt.setObjectName("smpBitsMode_txt")
        self.gridLayout_10.addWidget(self.smpBitsMode_txt, 1, 1, 1, 1)
        self.memoryVol = QtWidgets.QLabel(self.config_gbx)
        self.memoryVol.setObjectName("memoryVol")
        self.gridLayout_10.addWidget(self.memoryVol, 5, 0, 1, 1)
        self.sample_rate = QtWidgets.QLabel(self.config_gbx)
        self.sample_rate.setObjectName("sample_rate")
        self.gridLayout_10.addWidget(self.sample_rate, 0, 0, 1, 1)
        self.memoryVol_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.memoryVol_txt.setObjectName("memoryVol_txt")
        self.gridLayout_10.addWidget(self.memoryVol_txt, 5, 1, 1, 1)
        self.wordBits_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.wordBits_txt.setObjectName("wordBits_txt")
        self.gridLayout_10.addWidget(self.wordBits_txt, 4, 1, 1, 1)
        self.sectNum = QtWidgets.QLabel(self.config_gbx)
        self.sectNum.setObjectName("sectNum")
        self.gridLayout_10.addWidget(self.sectNum, 2, 0, 1, 1)
        self.wordBits = QtWidgets.QLabel(self.config_gbx)
        self.wordBits.setObjectName("wordBits")
        self.gridLayout_10.addWidget(self.wordBits, 4, 0, 1, 1)
        self.sectBits = QtWidgets.QLabel(self.config_gbx)
        self.sectBits.setObjectName("sectBits")
        self.gridLayout_10.addWidget(self.sectBits, 3, 0, 1, 1)
        self.smpBitsMode = QtWidgets.QLabel(self.config_gbx)
        self.smpBitsMode.setObjectName("smpBitsMode")
        self.gridLayout_10.addWidget(self.smpBitsMode, 1, 0, 1, 1)
        self.sectNum_txt = QtWidgets.QLineEdit(self.config_gbx)
        self.sectNum_txt.setObjectName("sectNum_txt")
        self.gridLayout_10.addWidget(self.sectNum_txt, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.config_gbx, 3, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 261, 618))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.sideband_sig_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.sideband_sig_input.setObjectName("sideband_sig_input")
        self.gridLayout_11.addWidget(self.sideband_sig_input, 3, 1, 1, 1)
        self.sig_angle_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.sig_angle_input.setObjectName("sig_angle_input")
        self.gridLayout_11.addWidget(self.sig_angle_input, 22, 1, 1, 1)
        self.fullscale_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.fullscale_input.setObjectName("fullscale_input")
        self.gridLayout_11.addWidget(self.fullscale_input, 4, 1, 1, 1)
        self.dbc_th_IL = QtWidgets.QLabel(self.groupBox_4)
        self.dbc_th_IL.setObjectName("dbc_th_IL")
        self.gridLayout_11.addWidget(self.dbc_th_IL, 15, 0, 1, 1)
        self.Rl = QtWidgets.QLabel(self.groupBox_4)
        self.Rl.setObjectName("Rl")
        self.gridLayout_11.addWidget(self.Rl, 5, 0, 1, 1)
        self.refclk_ratio = QtWidgets.QLabel(self.groupBox_4)
        self.refclk_ratio.setObjectName("refclk_ratio")
        self.gridLayout_11.addWidget(self.refclk_ratio, 21, 0, 1, 1)
        self.Rl_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.Rl_input.setObjectName("Rl_input")
        self.gridLayout_11.addWidget(self.Rl_input, 5, 1, 1, 1)
        self.imd_mode = QtWidgets.QLabel(self.groupBox_4)
        self.imd_mode.setObjectName("imd_mode")
        self.gridLayout_11.addWidget(self.imd_mode, 20, 0, 1, 1)
        self.sideband_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.sideband_input.setObjectName("sideband_input")
        self.gridLayout_11.addWidget(self.sideband_input, 2, 1, 1, 1)
        self.dc_1f_noise_cancel_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dc_1f_noise_cancel_input.setObjectName("dc_1f_noise_cancel_input")
        self.gridLayout_11.addWidget(self.dc_1f_noise_cancel_input, 23, 1, 1, 1)
        self.plot_option_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.plot_option_input.setObjectName("plot_option_input")
        self.gridLayout_11.addWidget(self.plot_option_input, 18, 1, 1, 1)
        self.ENOB_include_HD_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.ENOB_include_HD_input.setObjectName("ENOB_include_HD_input")
        self.gridLayout_11.addWidget(self.ENOB_include_HD_input, 17, 1, 1, 1)
        self.dbc_th_SFDR = QtWidgets.QLabel(self.groupBox_4)
        self.dbc_th_SFDR.setObjectName("dbc_th_SFDR")
        self.gridLayout_11.addWidget(self.dbc_th_SFDR, 16, 0, 1, 1)
        self.imd_mode_cmbox = QtWidgets.QComboBox(self.groupBox_4)
        self.imd_mode_cmbox.setObjectName("imd_mode_cmbox")
        self.imd_mode_cmbox.addItem("")
        self.imd_mode_cmbox.addItem("")
        self.gridLayout_11.addWidget(self.imd_mode_cmbox, 20, 1, 1, 1)
        self.sideband_sig = QtWidgets.QLabel(self.groupBox_4)
        self.sideband_sig.setObjectName("sideband_sig")
        self.gridLayout_11.addWidget(self.sideband_sig, 3, 0, 1, 1)
        self.sideband = QtWidgets.QLabel(self.groupBox_4)
        self.sideband.setObjectName("sideband")
        self.gridLayout_11.addWidget(self.sideband, 2, 0, 1, 1)
        self.num_IMD = QtWidgets.QLabel(self.groupBox_4)
        self.num_IMD.setObjectName("num_IMD")
        self.gridLayout_11.addWidget(self.num_IMD, 8, 0, 1, 1)
        self.dc_1f_noise_cancel = QtWidgets.QLabel(self.groupBox_4)
        self.dc_1f_noise_cancel.setObjectName("dc_1f_noise_cancel")
        self.gridLayout_11.addWidget(self.dc_1f_noise_cancel, 23, 0, 1, 1)
        self.ENOB_include_HD = QtWidgets.QLabel(self.groupBox_4)
        self.ENOB_include_HD.setObjectName("ENOB_include_HD")
        self.gridLayout_11.addWidget(self.ENOB_include_HD, 17, 0, 1, 1)
        self.refclk_ratio_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.refclk_ratio_input.setObjectName("refclk_ratio_input")
        self.gridLayout_11.addWidget(self.refclk_ratio_input, 21, 1, 1, 1)
        self.num_IMD_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.num_IMD_input.setObjectName("num_IMD_input")
        self.gridLayout_11.addWidget(self.num_IMD_input, 8, 1, 1, 1)
        self.sigbw_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.sigbw_input.setObjectName("sigbw_input")
        self.gridLayout_11.addWidget(self.sigbw_input, 0, 1, 1, 1)
        self.num_interleave_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.num_interleave_input.setObjectName("num_interleave_input")
        self.gridLayout_11.addWidget(self.num_interleave_input, 6, 1, 1, 1)
        self.dpdbw_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dpdbw_input.setObjectName("dpdbw_input")
        self.gridLayout_11.addWidget(self.dpdbw_input, 1, 1, 1, 1)
        self.dbc_th_HD_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dbc_th_HD_input.setObjectName("dbc_th_HD_input")
        self.gridLayout_11.addWidget(self.dbc_th_HD_input, 13, 1, 1, 1)
        self.dacOSR_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dacOSR_input.setObjectName("dacOSR_input")
        self.gridLayout_11.addWidget(self.dacOSR_input, 11, 1, 1, 1)
        self.dbc_th_HD = QtWidgets.QLabel(self.groupBox_4)
        self.dbc_th_HD.setObjectName("dbc_th_HD")
        self.gridLayout_11.addWidget(self.dbc_th_HD, 13, 0, 1, 1)
        self.figure_overwrite_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.figure_overwrite_input.setObjectName("figure_overwrite_input")
        self.gridLayout_11.addWidget(self.figure_overwrite_input, 19, 1, 1, 1)
        self.dbc_th_SFDR_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dbc_th_SFDR_input.setObjectName("dbc_th_SFDR_input")
        self.gridLayout_11.addWidget(self.dbc_th_SFDR_input, 16, 1, 1, 1)
        self.window = QtWidgets.QLabel(self.groupBox_4)
        self.window.setObjectName("window")
        self.gridLayout_11.addWidget(self.window, 9, 0, 1, 1)
        self.sigbw = QtWidgets.QLabel(self.groupBox_4)
        self.sigbw.setObjectName("sigbw")
        self.gridLayout_11.addWidget(self.sigbw, 0, 0, 1, 1)
        self.plot_range = QtWidgets.QLabel(self.groupBox_4)
        self.plot_range.setObjectName("plot_range")
        self.gridLayout_11.addWidget(self.plot_range, 12, 0, 1, 1)
        self.nyquitst_zone_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.nyquitst_zone_input.setObjectName("nyquitst_zone_input")
        self.gridLayout_11.addWidget(self.nyquitst_zone_input, 10, 1, 1, 1)
        self.num_HD = QtWidgets.QLabel(self.groupBox_4)
        self.num_HD.setObjectName("num_HD")
        self.gridLayout_11.addWidget(self.num_HD, 7, 0, 1, 1)
        self.num_interleave = QtWidgets.QLabel(self.groupBox_4)
        self.num_interleave.setObjectName("num_interleave")
        self.gridLayout_11.addWidget(self.num_interleave, 6, 0, 1, 1)
        self.plot_option = QtWidgets.QLabel(self.groupBox_4)
        self.plot_option.setObjectName("plot_option")
        self.gridLayout_11.addWidget(self.plot_option, 18, 0, 1, 1)
        self.plot_range_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.plot_range_input.setObjectName("plot_range_input")
        self.gridLayout_11.addWidget(self.plot_range_input, 12, 1, 1, 1)
        self.dbc_th_IMD_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dbc_th_IMD_input.setObjectName("dbc_th_IMD_input")
        self.gridLayout_11.addWidget(self.dbc_th_IMD_input, 14, 1, 1, 1)
        self.num_HD_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.num_HD_input.setObjectName("num_HD_input")
        self.gridLayout_11.addWidget(self.num_HD_input, 7, 1, 1, 1)
        self.sig_angle = QtWidgets.QLabel(self.groupBox_4)
        self.sig_angle.setObjectName("sig_angle")
        self.gridLayout_11.addWidget(self.sig_angle, 22, 0, 1, 1)
        self.fullscale = QtWidgets.QLabel(self.groupBox_4)
        self.fullscale.setObjectName("fullscale")
        self.gridLayout_11.addWidget(self.fullscale, 4, 0, 1, 1)
        self.figure_overwrite = QtWidgets.QLabel(self.groupBox_4)
        self.figure_overwrite.setObjectName("figure_overwrite")
        self.gridLayout_11.addWidget(self.figure_overwrite, 19, 0, 1, 1)
        self.dacOSR = QtWidgets.QLabel(self.groupBox_4)
        self.dacOSR.setObjectName("dacOSR")
        self.gridLayout_11.addWidget(self.dacOSR, 11, 0, 1, 1)
        self.dbc_th_IL_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dbc_th_IL_input.setObjectName("dbc_th_IL_input")
        self.gridLayout_11.addWidget(self.dbc_th_IL_input, 15, 1, 1, 1)
        self.dbc_th_IMD = QtWidgets.QLabel(self.groupBox_4)
        self.dbc_th_IMD.setObjectName("dbc_th_IMD")
        self.gridLayout_11.addWidget(self.dbc_th_IMD, 14, 0, 1, 1)
        self.nyquitst_zone = QtWidgets.QLabel(self.groupBox_4)
        self.nyquitst_zone.setObjectName("nyquitst_zone")
        self.gridLayout_11.addWidget(self.nyquitst_zone, 10, 0, 1, 1)
        self.dpdbw = QtWidgets.QLabel(self.groupBox_4)
        self.dpdbw.setObjectName("dpdbw")
        self.gridLayout_11.addWidget(self.dpdbw, 1, 0, 1, 1)
        self.window_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.window_input.setObjectName("window_input")
        self.gridLayout_11.addWidget(self.window_input, 9, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_3, 4, 0, 1, 1)
        self.gridLayout_8.setRowStretch(0, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setStyleSheet("backgroud-color:rgb(190, 198, 204)")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout.addWidget(self.textEdit_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "SETTINGS"))
        self.file_toolButton.setText(_translate("MainWindow", "..."))
        self.file_path_label.setText(_translate("MainWindow", "file_path"))
        self.tool_label.setText(_translate("MainWindow", "tool"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.config_gbx.setTitle(_translate("MainWindow", "config"))
        self.memoryVol.setText(_translate("MainWindow", "memoryVol"))
        self.sample_rate.setText(_translate("MainWindow", "sample_rate"))
        self.sectNum.setText(_translate("MainWindow", "sectNum"))
        self.wordBits.setText(_translate("MainWindow", "wordBits"))
        self.sectBits.setText(_translate("MainWindow", "sectBits"))
        self.smpBitsMode.setText(_translate("MainWindow", "smpBitsMode"))
        self.groupBox_4.setTitle(_translate("MainWindow", "param"))
        self.dbc_th_IL.setText(_translate("MainWindow", "dbc_th_IL"))
        self.Rl.setText(_translate("MainWindow", "Rl"))
        self.refclk_ratio.setText(_translate("MainWindow", "refclk_ratio"))
        self.imd_mode.setText(_translate("MainWindow", "imd_mode"))
        self.dbc_th_SFDR.setText(_translate("MainWindow", "dbc_th_SFDR"))
        self.imd_mode_cmbox.setItemText(0, _translate("MainWindow", "0"))
        self.imd_mode_cmbox.setItemText(1, _translate("MainWindow", "1"))
        self.sideband_sig.setText(_translate("MainWindow", "sideband_sig"))
        self.sideband.setText(_translate("MainWindow", "sideband"))
        self.num_IMD.setText(_translate("MainWindow", "num_IMD"))
        self.dc_1f_noise_cancel.setText(_translate("MainWindow", "dc_1f_noise_cancel"))
        self.ENOB_include_HD.setText(_translate("MainWindow", "ENOB_include_HD"))
        self.dbc_th_HD.setText(_translate("MainWindow", "dbc_th_HD"))
        self.window.setText(_translate("MainWindow", "window"))
        self.sigbw.setText(_translate("MainWindow", "sigbw"))
        self.plot_range.setText(_translate("MainWindow", "plot_range"))
        self.num_HD.setText(_translate("MainWindow", "num_HD"))
        self.num_interleave.setText(_translate("MainWindow", "num_interleave"))
        self.plot_option.setText(_translate("MainWindow", "plot_option"))
        self.sig_angle.setText(_translate("MainWindow", "sig_angle"))
        self.fullscale.setText(_translate("MainWindow", "fullscale"))
        self.figure_overwrite.setText(_translate("MainWindow", "figure_overwrite"))
        self.dacOSR.setText(_translate("MainWindow", "dacOSR"))
        self.dbc_th_IMD.setText(_translate("MainWindow", "dbc_th_IMD"))
        self.nyquitst_zone.setText(_translate("MainWindow", "nyquitst_zone"))
        self.dpdbw.setText(_translate("MainWindow", "dpdbw"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% vin            input</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% fs             total sample rate , for dac, fs=actual dac fs*dacOSR</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% resolution     adc resolution,resolution=0 for dac</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% sigbw          noise calc bw</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% dpdbw          noise calc bw</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% sideband       +/-sideband for every tone, default 100KHz</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% resolution     adc resolution,resolution=0 for dac</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% fullscale      voltage fullscale, mvpp</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% Rl             equivalent R load,default 100ohm</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% num_interleave </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% num_HD</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% window         \'non\' \'hann\' \'black\'</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% nyquitst_zone  for rfadc, use this to set correct freq range;for dac set to 1 to avoid errors</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% dacOSR         for dac simulation only, only HD/IL fold to first nyquist zone will be calc/marked</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% plot_range     for dac, 0 \'full\' zone , 1 first , 2 first+sencond...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% dbc_th_HD dbc_th_IMD dbc_th_IL dbc_th_SFDR  threshold for whether highlight relative values</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% ENOB_include_HD   whether ENOB include HD</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% plot_option       plot figure or not</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% figure_overwrite  if overwrite=1 figure will always use figure 1 to overwrite last plot</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">% dc_1f_noise_cancel=20e6; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%para%%%%%%%%%%%%%%%%%%%%%%%%%%%%%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'sigbw\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sigbw=para.sigbw;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sigbw=[0 fs/2];</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dpdbw\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dpdbw=para.dpdbw;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dpdbw=[0 fs/2];</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'sideband\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sideband=para.sideband;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sideband=100e3;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'sideband_sig\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sideband_sig=para.sideband_sig;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sideband_sig=100e3;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'fullscale\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    fullscale=para.fullscale;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    fullscale=1000;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'Rl\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Rl=para.Rl;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Rl=100;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'num_interleave\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_interleave=para.num_interleave;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_interleave=1;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'num_HD\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_HD=para.num_HD;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_HD=7;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'num_IMD\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_IMD=para.num_IMD;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    num_IMD=5;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'window\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    window=para.window;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    window=\'non\';</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'nyquitst_zone\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    nyquist_zone=para.nyquitst_zone;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    nyquist_zone=1;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dacOSR\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dacOSR=para.dacOSR;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dacOSR=1;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'plot_range\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    plot_range=para.plot_range;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    plot_range=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dbc_th_HD\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_HD=para.dbc_th_HD;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_HD=-70;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dbc_th_IMD\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_IMD=para.dbc_th_IMD;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_IMD=-70;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dbc_th_IL\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_IL=para.dbc_th_IL;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_IL=-70;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dbc_th_SFDR\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_SFDR=para.dbc_th_SFDR;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dbc_th_SFDR=70;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'ENOB_include_HD\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    ENOB_include_HD=para.ENOB_include_HD;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    ENOB_include_HD=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'plot_option\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    plot_option=para.plot_option;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    plot_option=1;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'figure_overwrite\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    figure_overwrite=para.figure_overwrite;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    figure_overwrite=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'imd_mode\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    imd_mode=para.imd_mode;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    imd_mode=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'refclk_ratio\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    refclk_ratio=para.refclk_ratio;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    refclk_ratio=1;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'sig_angle\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sig_angle=para.sig_angle;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    sig_angle=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if isfield(para,\'dc_1f_noise_cancel\')</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dc_1f_noise_cancel=para.dc_1f_noise_cancel;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">else</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    dc_1f_noise_cancel=0;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end      %% add cancel dc  and 1/f noise</p></body></html>"))
import ui_pr_rc
