# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ApplyChanges = QtWidgets.QPushButton(self.groupBox_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ApplyChanges.setIcon(icon)
        self.ApplyChanges.setObjectName("ApplyChanges")
        self.gridLayout_12.addWidget(self.ApplyChanges, 1, 0, 1, 1)
        self.Export = QtWidgets.QPushButton(self.groupBox_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export.setIcon(icon1)
        self.Export.setObjectName("Export")
        self.gridLayout_12.addWidget(self.Export, 1, 3, 1, 1)
        self.Resetchip = QtWidgets.QPushButton(self.groupBox_5)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Reset-Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Resetchip.setIcon(icon2)
        self.Resetchip.setObjectName("Resetchip")
        self.gridLayout_12.addWidget(self.Resetchip, 1, 1, 1, 1)
        self.software_defaults = QtWidgets.QPushButton(self.groupBox_5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.software_defaults.setIcon(icon3)
        self.software_defaults.setObjectName("software_defaults")
        self.gridLayout_12.addWidget(self.software_defaults, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 1, 5, 1, 1)
        self.search_register = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_register.setObjectName("search_register")
        self.gridLayout_12.addWidget(self.search_register, 2, 0, 1, 5)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.func_descibe = QtWidgets.QTreeWidget(self.centralwidget)
        self.func_descibe.setAutoScrollMargin(16)
        self.func_descibe.setObjectName("func_descibe")
        self.func_descibe.header().setCascadingSectionResizes(False)
        self.func_descibe.header().setDefaultSectionSize(160)
        self.verticalLayout.addWidget(self.func_descibe)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ApplyChanges.setText(_translate("MainWindow", "ApplyChanges"))
        self.Export.setText(_translate("MainWindow", "Export"))
        self.Resetchip.setText(_translate("MainWindow", "Reset Chip"))
        self.software_defaults.setText(_translate("MainWindow", "Software Defaults"))
        self.func_descibe.headerItem().setText(0, _translate("MainWindow", "Address(Hex)"))
        self.func_descibe.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.func_descibe.headerItem().setText(2, _translate("MainWindow", "Functional Group "))
        self.func_descibe.headerItem().setText(3, _translate("MainWindow", "Data(Hex)"))
        self.func_descibe.headerItem().setText(4, _translate("MainWindow", "Data(Binary)"))
        self.func_descibe.headerItem().setText(5, _translate("MainWindow", "Tools"))
import ui_pr_rc
